### ISSUE TITLE
what is the default Propagation?

### ISSUE THREAD

**Issue by Diluka** [odavid/typeorm-transactional-cls-hooked#34]
I use default Propagation which pass nothing to `@Transactional()`. I consider it is `REQUIRED`. But when I use a decorated method to call another decorated method cause a deadlock. `TypeORM` logs two `START TRANSACTION`. it means the default Propagation is `REQUIRES_NEW`? Or it is a bug?

**Comment by odavid** [comment]
Hi @Diluka, the default propagation is REQUIRED. Looking at the code, I don’t really see a way for this behavior to happen. I will be afk for quite long time, so I cannot test that at the moment. Will try to when I have the chance, but since I tested that before and nothing changed in that area, I doubt I can reproduce that. Can it be that you are running another asynchronous transaction?

**Comment by Diluka** [comment]
just use this trans, maybe typeorm dont support nested

EL PYS CONGROO

________________________________
发件人: Ohad David <notifications@github.com>
发送时间: 星期三, 十二月 4, 2019 5:25 下午
收件人: odavid/typeorm-transactional-cls-hooked
抄送: Diluka; Mention
主题: Re: [odavid/typeorm-transactional-cls-hooked] what is the default Propagation? (#34)


Hi @Diluka<https://github.com/Diluka>, the default propagation is REQUIRED. Looking at the code, I don’t really see a way for this behavior to happen. I will be afk for quite long time, so I cannot test that at the moment. Will try to when I have the chance, but since I tested that before and nothing changed in that area, I doubt I can reproduce that. Can it be that you are running another asynchronous transaction?

―
