### ISSUE TITLE
Does this library work with both InjectRepository and createQueryBuilder

### ISSUE THREAD

**Issue by yayajacky** [odavid/typeorm-transactional-cls-hooked#39]
Hi:

Nice library you got here! On one of my project, we use an encapsulation pattern where each Repo class gets the typeorm repository injected in the constructor.

@Injectable()
export class UserRepo {
  constructor(
    @InjectRepository(User) private readonly repository: Repository<User>
  ) {}
}

Then, somewhere below, we have a method like this:

@Transactional()
  async lockUserById(id: string): Promise<User[]> {
    const users = await this.repository
      .createQueryBuilder('user')
      .select(`user.id`)
      .where(`user.id = :userId`, { id })
      .setLock('pessimistic_write')
      .getMany()
    return alerts
  }

When multiple execution happens, it seems they are all able to pass lockUserById and go on to insert user records instead of waiting.

Then, all but one of them will rollback and retry again.

Does this mean transaction is applied correctly to the injected Repository?

We do use:
initializeTransactionalContext() // Initialize cls-hooked
patchTypeORMRepositoryWithBaseRepository() // patch Repository with BaseRepository.

At the beginning.

And this is MYSQL

Thanks!

**Comment by odavid** [comment]
Thank you!
The `Transactional` code is very simple. It just pushes the current EntityManager into a cls-hooked context and uses it along the way. I am not sure I understand the issue you have, but, the answer to your main question: *Yes*, the `@Transactional` should work with `InjectRepository` and [`repository.createQueryBuilder()`](https://github.com/typeorm/typeorm/blob/master/src/repository/Repository.ts#L49), since it uses the same EntityManager. 
One think I noticed in your code, is that you are using the transactional on the `lockUserById`, which seems odd to me, since at the end of the method, the transaction will be either committed or  rolled back. The `@Transactional` should wrap the upper level method IMHO.

Hope it helps...

**Comment by yayajacky** [comment]
Thank you so much for the reply!

We also put @Transactional on the method on the outside, does putting it on the ones inside cause the lock to be released?

Good to hear that InjectRepository and repository.createQueryBuilder() should work, thanks
